name: accenture
recipe: drupal9
config:
  webroot: web
  composer_version: '2'
  php: '8.1'
  drush: true
  xdebug: false
tooling:
  drush:
    service: appserver
    description: Run Drush commands
    cmd:
      - /app/vendor/bin/drush
services:
  appserver:
    build:
      - composer instal      
