# Schema for the configuration files of the AC REST API module.
ac_rest_api.settings:
  type: config_object
  label: 'AC REST API settings'
  mapping:
    example:
      type: string
      label: 'Example'
